SELECT
  USED_GOODS_USER.USER_ID,
  # COUNT(USED_GOODS_BOARD.BOARD_ID),
  USED_GOODS_USER.NICKNAME,
  CONCAT(USED_GOODS_USER.CITY, ' ',USED_GOODS_USER.STREET_ADDRESS1, ' ', USED_GOODS_USER.STREET_ADDRESS2) AS 전체주소,
  CONCAT(SUBSTR(USED_GOODS_USER.TLNO, 1, 3), '-', SUBSTR(USED_GOODS_USER.TLNO, 4, 4), '-', SUBSTR(USED_GOODS_USER.TLNO, 8, 4)) AS 전화번호
FROM
  USED_GOODS_USER
JOIN
  USED_GOODS_BOARD
ON 
  USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID
GROUP BY
  USED_GOODS_USER.USER_ID,
  USED_GOODS_USER.NICKNAME
HAVING 
  COUNT(*) >= 3
ORDER BY 
  USED_GOODS_USER.USER_ID DESC;