SELECT
  BOOK.CATEGORY,
  SUM(BOOK_SALES.SALES) as TOTAL_SALES
FROM
  BOOK
JOIN
  BOOK_SALES
ON
  BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE
  BOOK_SALES.SALES_DATE >= '2022-01-01'
  AND
  BOOK_SALES.SALES_DATE < '2022-02-01'
GROUP BY
  BOOK.CATEGORY
ORDER BY
  BOOK.CATEGORY ASC