SELECT
    R.CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY R
JOIN
    CAR_RENTAL_COMPANY_CAR C
ON
    C.CAR_ID = R.CAR_ID
WHERE
    R.START_DATE >= '2022-10-01'
    AND C.CAR_TYPE = '세단'
GROUP BY
    C.CAR_ID
ORDER BY
    R.CAR_ID DESC
    